---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: cache
spec:
  ports:
    - port: 80
  selector:
    app: nginx
    tier: cache
  type: LoadBalancer
---
apiVersion: apps/v1   # versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: cache
spec:
  selector:
    matchLabels:
      app: nginx
      tier: cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: cache
    spec:
      containers:
        - image: epynic/do-k8s-challenge-nginx:${IMAGETAG}
          name: nginx
          ports:
            - containerPort: 80
              name: nginx
          # volumeMounts:
          #   - name: wordpress-persistent-storage
          #     mountPath: /var/www/html
      # volumes:
      #   - name: wordpress-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: wp-pv-claim
